### ISSUE TITLE
example.py doesn't function

### ISSUE THREAD

**Issue by fennecinspace** [arpesenti/exposure_fusion#1]
I cloned the repository and did :

```
python3 example.py
```

This was the result :

```
Traceback (most recent call last):
  File "example.py", line 10, in <module>
    aligned_images = align_images(images)
  File "/home/hammi/Desktop/exposure_fusion/exposure_fusion.py", line 187, in align_images
    (cc, warp_matrix) = cv2.findTransformECC(model_image, gray_images[i], warp_matrix, warp_mode, criteria)
TypeError: Required argument 'inputMask' (pos 6) not found
```

I'm on python 3.6.9

I also tried python 2.7 and get an error as well.

**Comment by arpesenti** [comment]
Thanks, it should be fixed now.
